table Table
	lineageTag: e4e63615-8ce6-4189-be2a-7eb016d83158

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 5b1427c4-34b2-45fd-a9f8-4cc259ba3d45
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Number
		dataType: int64
		formatString: 0
		lineageTag: e08fcc3e-48fe-43d9-880b-d8ace1673d7e
		summarizeBy: sum
		sourceColumn: Number

		annotation SummarizationSetBy = Automatic

	column Text
		dataType: string
		lineageTag: 661e536c-99c6-41a4-be1d-f51aed8bd55f
		summarizeBy: none
		sourceColumn: Text

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("RYwxDoAgDEXv0pnBoiCepWFgMLCqQ69vf4lxKMl7r1SEmAKtNu3prVMNQtGIS0LQ5ga92My+oe/4olMkFzCOGYhnqDNCjj/jUsw4f+twc2DDxaXjk7xgD/akWl8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Number = _t, Text = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"Number", Int64.Type}, {"Text", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

