from dataclasses import dataclass
from typing import List, Tuple, Optional, Dict, Any, Set, Union, Iterable, Literal
import math

import numpy as np
from PIL import Image, ImageDraw

# ------------------------------
# Core data structures
# ------------------------------

@dataclass(frozen=True)
class HexCoord:
    """
    Axial coordinates (q, r) for hex grid.
    s = -q - r (implicit).
    """
    q: int
    r: int


@dataclass(frozen=True)
class VelocityState:
    """
    Velocity vector at a node, including magnitude and direction.
    direction is an integer encoding from 0-5; None at the start node by convention.
    """
    magnitude: float      # speed
    direction: int        # heading angle ordinal


@dataclass
class Node:
    """
    Search node for H* on a hex grid.
    """
    location: HexCoord
    velocity: VelocityState
    parent: Optional["Node"] = None

    step_distance: Optional[float] = None  # The distance traveled from parent

    # Costs (optional, can be maintained externally)
    g_cost: float = 0.0  # actual travel time accumulated
    h_cost: float = 0.0  # heuristic travel time
    f_cost: float = 0.0  # total estimated cost


# ------------------------------
# Problem / environment model
# ------------------------------



DIRECTIONS: Tuple[Tuple[int, int], ...] = (
    ( 1,  0),  # 0: E
    ( 1, -1),  # 1: SE
    ( 0, -1),  # 2: SW
    (-1,  0),  # 3: W
    (-1,  1),  # 4: NW
    ( 0,  1),  # 5: NE
)




class HexGrid:
    """
    Hexagonal grid environment using axial coordinates.
    Responsible for neighbor generation and obstacle queries.
    """

    def __init__(
        self,
        hex_size: float,
        obstacles: Optional[Dict[HexCoord, bool]] = None,
        allowed: Optional[Set[HexCoord]] = None,  
    ) -> None:
        self.hex_size = hex_size
        self.obstacles = obstacles or {}
        self.allowed = allowed  # None => unbounded

    def is_blocked(self, coord: HexCoord) -> bool:
        """Return True if the cell is blocked or out of bounds (if bounds exist)."""
        #if self.allowed is not None and coord not in self.allowed:
        #    return True
        return coord in self.obstacles



    def neighbors(self, coord: HexCoord) -> List[HexCoord]:
        """
        Return the six adjacent axial coordinates (filtering out blocked ones).

        Uses pointy-top axial directions:
            (+1,  0), (+1, -1), (0, -1),
            (-1,  0), (-1, +1), (0, +1)

        Any neighbor for which `is_blocked(nei)` returns True will be excluded.
        """


        q0, r0 = coord.q, coord.r
        result: List[HexCoord] = []
        for dq, dr in DIRECTIONS:
            nei = HexCoord(q0 + dq, r0 + dr)
            if not self.is_blocked(nei):
                result.append(nei)
        return result


def cube_round(xf: float, yf: float, zf: float) -> Tuple[int, int, int]:
    """Round fractional cube coords to integer cube coords with x+y+z=0 constraint."""
    rx, ry, rz = round(xf), round(yf), round(zf)

    x_diff = abs(rx - xf)
    y_diff = abs(ry - yf)
    z_diff = abs(rz - zf)

    if x_diff > y_diff and x_diff > z_diff:
        rx = -ry - rz
    elif y_diff > z_diff:
        ry = -rx - rz
    else:
        rz = -rx - ry

    return int(rx), int(ry), int(rz)

def cube_to_axial(x: int, y: int, z: int) -> HexCoord:
    """Cube -> axial (q=x, r=z)."""
    return HexCoord(x, z)

def hex_line_one_side(a: HexCoord, b: HexCoord, *, eps: float) -> List[HexCoord]:
    """
    Standard hex line draw (ordered), but with a tiny epsilon nudge to force a consistent
    tie-break side on boundaries.
    """
    ax, ay, az = axial_to_cube(a)  # uses your existing function
    bx, by, bz = axial_to_cube(b)

    n = max(abs(ax - bx), abs(ay - by), abs(az - bz))
    if n == 0:
        return [a]

    out: List[HexCoord] = []
    for i in range(n + 1):
        t = i / n
        xf = ax + (bx - ax) * t
        yf = ay + (by - ay) * t
        zf = az + (bz - az) * t

        # Nudge while preserving x+y+z=0.
        # Two parities are generated by eps=+1e-6 and eps=-1e-6.
        xf += eps
        yf += eps
        zf -= 2.0 * eps

        rx, ry, rz = cube_round(xf, yf, zf)
        out.append(cube_to_axial(rx, ry, rz))

    # De-dupe consecutive repeats (can happen due to rounding ties)
    deduped = [out[0]]
    for h in out[1:]:
        if h != deduped[-1]:
            deduped.append(h)

    return deduped

def hexes_in_between_solid(
    a: HexCoord,
    b: HexCoord,
    *,
    include_endpoints: bool = False,
    eps: float = 1e-6,
) -> Set[HexCoord]:
    """
    "Solid" (supercover-ish) set of hexes between a and b:
    union of left-parity and right-parity line draws.

    - include_endpoints=False excludes a and b
    """
    line_l = hex_line_one_side(a, b, eps=+eps)
    line_r = hex_line_one_side(a, b, eps=-eps)

    s = set(line_l) | set(line_r)

    if not include_endpoints:
        s.discard(a)
        s.discard(b)
    return s
def get_available_nodes_in_dir(
    start: HexCoord,
    direction: int,
    obs: Union[Set[HexCoord], Iterable[HexCoord], Dict[HexCoord, bool]],
    obs_radius: int,
    include_start: bool = True,
    ray_range: Optional[int] = None,   # <-- NEW: cap number of returned nodes
) -> Set[HexCoord]:
    """
    Return a set of nodes along a ray starting at `start` stepping in `direction`
    until the next node would be within `obs_radius` (hex steps) of any obstacle.

    If `ray_range` is not None, return at most that many nodes (still stopping
    early if an unsafe node is encountered).

    - direction: 0..5 using the global DIRECTIONS
    - obs: set/iterable of HexCoord, or dict[HexCoord, bool] (like your obstacle maps)
    - obs_radius: non-negative integer. 0 means "stop when you hit an obstacle cell".
    - include_start: if False, `start` is not included (even if safe).
    - ray_range: optional non-negative integer cap on number of nodes returned.
        * ray_range = 0 -> returns empty set
        * include_start=True, ray_range=1 -> may return {start} if safe
        * include_start=False, ray_range=1 -> may return {start + step} if safe
        * ray_range=None -> preserves current behavior (unbounded except MAX_STEPS)
    """
    if obs_radius < 0:
        raise ValueError("obs_radius must be a non-negative integer")

    if ray_range is not None:
        if not isinstance(ray_range, int):
            raise TypeError("ray_range must be an int or None")
        if ray_range < 0:
            raise ValueError("ray_range must be a non-negative integer")

    # Normalize obs to a set of HexCoord (supports dict obstacle maps)
    if isinstance(obs, dict):
        obs_set: Set[HexCoord] = set(obs.keys())
    else:
        obs_set = set(obs)

    # If there are no obstacles and ray_range is None, the ray is unbounded; we must cap it.
    MAX_STEPS = 10000

    # Precompute a "danger zone" if it’s cheaper than checking all obstacles each step.
    use_precompute = (obs_radius > 0 and len(obs_set) * (obs_radius ** 2) < 200000)

    if use_precompute:
        danger: Set[HexCoord] = set()
        for o in obs_set:
            danger |= hex_disk(o, obs_radius)   # already defined in your file

        def is_safe(c: HexCoord) -> bool:
            return c not in danger
    else:
        def is_safe(c: HexCoord) -> bool:
            for o in obs_set:
                if hdist(c, o) <= obs_radius:
                    return False
            return True

    # Walk the ray
    out: Set[HexCoord] = set()
    step = DIRECTIONS[direction % 6]

    # If excluding start, begin from the first step away from start.
    curr = start if include_start else add_coords(start, step)

    # Determine how many nodes to attempt to collect.
    # - If ray_range is None: preserve existing behavior (cap by MAX_STEPS).
    # - If ray_range is provided: attempt exactly that many (or stop early if unsafe).
    if ray_range is None:
        limit = MAX_STEPS + 1
    else:
        limit = ray_range

    for _ in range(limit):
        if not is_safe(curr):
            break
        out.add(curr)
        curr = add_coords(curr, step)

    return out

# ------------------------------
# Hex Geometry Functions
# ------------------------------        

def add_coords(a: HexCoord, step: Tuple[int, int]) -> HexCoord:
    """
    Element-wise addition of axial coordinate and step.
    """
    dq, dr = step
    return HexCoord(a.q+dq, a.r+dr)

def get_direction(prev: HexCoord, nxt: HexCoord) -> int:
    """
    Return the direction index (0..5) of the unit step from `prev` to `nxt`,
    according to the DIRECTIONS tuple.

    Raises:
        ValueError: if `nxt` is not an immediate neighbor of `prev` (i.e., the
                    delta doesn't match any unit direction).
    """
    dq = nxt.q - prev.q
    dr = nxt.r - prev.r
    try:
        return DIRECTIONS.index((dq, dr))
    except ValueError as e:
        raise ValueError(
            f"{prev} -> {nxt} is not a single-step neighbor; delta=({dq},{dr})"
        ) from e

def get_direction_ray(prev: HexCoord, nxt: HexCoord) -> int:
    """
    Return the direction index (0..5) of the straight-line axial ray from `prev` to `nxt`.

    Works when `nxt` is multiple steps away, but only if the displacement lies exactly
    along one of the 6 axial directions. Raises ValueError if not axially aligned.

    Notes
    -----
    For axial coords (q,r), the 6 rays are:
      - dq > 0, dr == 0            -> ( 1,  0)  index 0
      - dq > 0, dr < 0, dq == -dr  -> ( 1, -1)  index 1
      - dq == 0, dr < 0            -> ( 0, -1)  index 2
      - dq < 0, dr == 0            -> (-1,  0)  index 3
      - dq < 0, dr > 0, -dq == dr  -> (-1,  1)  index 4
      - dq == 0, dr > 0            -> ( 0,  1)  index 5
    """
    dq = nxt.q - prev.q
    dr = nxt.r - prev.r

    if dq == 0 and dr == 0:
        raise ValueError(f"{prev} -> {nxt} has zero displacement")

    # Axis q
    if dr == 0:
        return 0 if dq > 0 else 3

    # Axis r
    if dq == 0:
        return 5 if dr > 0 else 2

    # Diagonal axis: dq + dr == 0  (i.e., dq == -dr)
    if dq + dr == 0:
        return 1 if dq > 0 else 4

    raise ValueError(
        f"{prev} -> {nxt} is not axially aligned; delta=({dq},{dr})"
    )



def hex_segment_between(
    prev: HexCoord,
    nxt: HexCoord,
    *,
    include_prev: bool = True,
    include_next: bool = True,
) -> List[HexCoord]:
    """
    Return an ordered list of all axial hex coordinates on the straight segment
    from `prev` to `nxt` (inclusive/exclusive per flags), assuming axial alignment.

    Ordered from prev -> nxt.

    Raises ValueError if `prev` and `nxt` are not axially aligned.
    """
    dq = nxt.q - prev.q
    dr = nxt.r - prev.r

    # Degenerate case: same cell
    if dq == 0 and dr == 0:
        # If either endpoint is included, it's the same coordinate anyway.
        return [prev] if (include_prev or include_next) else []

    dir_idx, steps = _aligned_dir_and_steps(dq, dr)  # steps >= 1
    step = DIRECTIONS[dir_idx]

    start_i = 0 if include_prev else 1
    end_i = steps if include_next else (steps - 1)

    if end_i < start_i:
        return []

    out: List[HexCoord] = []
    curr = prev

    # Move to the first included index (start_i)
    for _ in range(start_i):
        curr = add_coords(curr, step)

    # Append indices start_i .. end_i
    for _ in range(start_i, end_i + 1):
        out.append(curr)
        curr = add_coords(curr, step)

    return out


def _aligned_dir_and_steps(dq: int, dr: int) -> Tuple[int, int]:
    """
    Given delta (dq, dr), return (dir_idx, k) where:
      (dq, dr) == k * DIRECTIONS[dir_idx], k >= 1
    Only valid for axial-aligned deltas. Raises ValueError otherwise.
    """
    # Axis q: (±1, 0)
    if dr == 0:
        if dq > 0:
            return 0, dq           # (1, 0) repeated dq times
        else:
            return 3, -dq          # (-1, 0) repeated -dq times

    # Axis r: (0, ±1)
    if dq == 0:
        if dr > 0:
            return 5, dr           # (0, 1) repeated dr times
        else:
            return 2, -dr          # (0, -1) repeated -dr times

    # Diagonal axis: dq + dr == 0  => (1, -1) or (-1, 1)
    if dq + dr == 0:
        if dq > 0:
            return 1, dq           # (1, -1) repeated dq times
        else:
            return 4, -dq          # (-1, 1) repeated -dq times

    raise ValueError(f"Not axially aligned: delta=({dq},{dr})")


def _aligned_dir_and_steps(dq: int, dr: int) -> Tuple[int, int]:
    """
    Given delta (dq, dr), return (dir_idx, k) where:
      (dq, dr) == k * DIRECTIONS[dir_idx], k >= 1
    Only valid for axial-aligned deltas. Raises ValueError otherwise.
    """
    # Axis q: (±1, 0)
    if dr == 0:
        if dq > 0:
            return 0, dq
        else:
            return 3, -dq

    # Axis r: (0, ±1)
    if dq == 0:
        if dr > 0:
            return 5, dr
        else:
            return 2, -dr

    # Diagonal axis: dq + dr == 0  => directions (1,-1) or (-1,1)
    if dq + dr == 0:
        if dq > 0:
            return 1, dq   # (1, -1) repeated dq times
        else:
            return 4, -dq  # (-1, 1) repeated -dq times

    raise ValueError(f"Not axially aligned: delta=({dq},{dr})")
def get_path_direction(prev: HexCoord, current: HexCoord, nxt: HexCoord) -> float:
    """
    Returns the path direction *at* `current` as a float index into DIRECTIONS,
    allowing half-step indices (e.g., 0.5) for zigzag straight-line approximations.

    Semantics
    ---------
    - Straight (same incoming and outgoing direction):
        return i  (i in {0,1,2,3,4,5})
    - Zigzag (adjacent unit directions, i.e., ±1 mod 6):
        return i ± 0.5  (midpoint between the two indices on the circle)
    - Turn (120°/180° change, i.e., ±2 or 3 mod 6):
        return i_out  (use the new, outgoing direction at `current`)

    Raises:
        ValueError: if any pair (prev,current) or (current,nxt) is not single-step adjacent.
    """
    if current == prev or current == nxt:
        raise ValueError("`current` must differ from `prev` and `nxt`")

    # Get unit direction indices for the incoming and outgoing steps.
    i_in = get_direction(prev, current)      # prev -> current
    i_out = get_direction(current, nxt)      # current -> nxt

    # Straight: keep the same integer index
    if i_in == i_out:
        return float(i_out)

    # Work on the circle Z_6
    diff = (i_out - i_in) % 6  # in {1,2,3,4,5}

    # Zigzag (60° left/right): midpoint between adjacent directions.
    # diff == 1 means rotate +60°; diff == 5 means rotate -60° (equivalently +300°).
    if diff == 1:
        # midpoint forward (i + 0.5), wrap to [0,6)
        return (i_in + 0.5) % 6.0
    if diff == 5:
        # midpoint backward (i - 0.5) == (i + 5.5) mod 6
        return (i_in - 0.5) % 6.0

    # Sharp turn (120°) or U-turn (180°): use outgoing heading (integer index).
    # diff == 2 or 4 -> 120°, diff == 3 -> 180° (backtrack)
    return float(i_out)



def get_neighbors_at_radius(center: "HexCoord", radius: int) -> Set["HexCoord"]:
    if radius < 0:
        raise ValueError("radius must be a non-negative integer")
    if radius == 0:
        return {center}

    # start at a consistent corner that matches the side-walk order below
    start = add_coords(center, (radius * DIRECTIONS[4][0], radius * DIRECTIONS[4][1]))

    ring: Set["HexCoord"] = set()
    curr = start

    for side in range(6):
        dq, dr = DIRECTIONS[side]
        for _ in range(radius):
            ring.add(curr)
            curr = add_coords(curr, (dq, dr))
    return ring

def get_neighbors_at_radius_ordered(center: "HexCoord", radius: int) -> List["HexCoord"]:
    if radius < 0:
        raise ValueError("radius must be a non-negative integer")
    if radius == 0:
        return [center]  
        
    start = add_coords(center, (radius * DIRECTIONS[0][0], radius * DIRECTIONS[0][1]))

    ring: List["HexCoord"] = []
    curr = start

    for side in range(-4, 2):
        dq, dr = DIRECTIONS[side]
        for _ in range(radius):
            ring.append(curr)
            curr = add_coords(curr, (dq, dr))
    return ring

def primitive_ray(dir_vec: HexCoord) -> HexCoord:
    """
    Reduce an axial direction vector to its primitive ray direction by dividing
    cube (x,y,z) by gcd(|x|,|y|,|z|), then returning axial (q=x, r=z).

    Examples:
      (2, 0)   -> (1, 0)
      (2,-1)   -> (2,-1)  (already primitive)
      (4,-2)   -> (2,-1)
    """
    x, y, z = axial_to_cube(dir_vec)  # ✅ your existing function
    g = math.gcd(math.gcd(abs(x), abs(y)), abs(z))
    if g == 0:
        return HexCoord(0, 0)
    return HexCoord(x // g, z // g)   # back to axial (q=x, r=z)


def gcd_reduce(action: HexCoord) -> HexCoord:
    """
    Reduce axial vector to its primitive step.
    Examples:
      (2, 0)   -> (1, 0)
      (12, -1) -> (12, -1)   (already primitive; gcd is 1)
      (3, -3)  -> (1, -1)
    """
    dq, dr = action.q, action.r
    if dq == 0 and dr == 0:
        raise ValueError("Zero vector has no direction")

    ds = -dq - dr
    g = math.gcd(math.gcd(abs(dq), abs(dr)), abs(ds))
    return HexCoord(dq // g, dr // g), g
    
def unique_direction_vectors_up_to_n(
    center: HexCoord,
    n: int,
    *,
    hex_size_for_angle: float = 1.0,
) -> List[HexCoord]:
    """
    Return unique direction vectors (axial offsets) up to radius n,
    removing redundant collinear endpoints via primitive-ray reduction.

    - Uses your get_neighbors_at_radius_ordered() for each radius 1..n
    - Uses your axial_to_cube() for gcd reduction
    - Uses your axial_to_xy() to sort by ascending angle from q+ (1,0)

    The returned vectors are OFFSETS (dq, dr) from center.
    """
    if n < 0:
        raise ValueError("n must be non-negative")

    # primitive ray -> representative offset (first seen = smallest radius)
    reps: Dict[HexCoord, HexCoord] = {}

    for radius in range(1, n + 1):
        ring = get_neighbors_at_radius_ordered(center, radius)
        for p in ring:
            off = HexCoord(p.q - center.q, p.r - center.r)
            prim = primitive_ray(off)
            if prim not in reps:
                reps[prim] = off

    def angle_from_qplus(v: HexCoord) -> float:
        # Sort by the ray angle (use primitive to be stable)
        prim = primitive_ray(v)
        x, y = axial_to_xy(prim, hex_size=hex_size_for_angle)  # ✅ your existing function
        ang = -math.atan2(y, x)
        return ang + 2.0 * math.pi if ang < 0 else ang

    out = sorted(reps.values(), key=angle_from_qplus)

    # Rotate so q+ (1,0) is at index 0, if present.
    # (It should be present for any n>=1, but this makes it robust.)
    target = HexCoord(1, 0)
    for i, v in enumerate(out):
        if primitive_ray(v) == target:
            out = out[i:] + out[:i]
            break

    return out

def circular_slice(seq, start, end):
    """
    Return a circular slice of seq for the half-open interval [start, end),
    wrapping around both ends as needed.

    Works like seq[start:end] but circular.
    """
    n = len(seq)
    if n == 0:
        return []

    length = end - start
    if length <= 0:
        return []

    start_mod = start % n
    end_mod = (start_mod + length) % n

    if length >= n:
        # If you ask for >= one full revolution, define your preference.
        # Here: return exactly 'length' elements by cycling.
        return [seq[(start + i) % n] for i in range(length)]

    if start_mod < end_mod:
        return list(seq[start_mod:end_mod])
    else:
        # wraps across the end
        return list(seq[start_mod:]) + list(seq[:end_mod])

def totient(n: int) -> int:
    """Euler's totient φ(n) via prime factorization (O(sqrt(n)) per n).

    Given n, the n-step parameter of Hex Star
    returns offset, the value to +/- the direction idx to get the candidate idxs
    """
    if n == 0:
        return 0
    if n <= 0:
        raise ValueError("n must be positive")
    result = n
    p = 2
    x = n
    while p * p <= x:
        if x % p == 0:
            while x % p == 0:
                x //= p
            result -= result // p
        p += 1 if p == 2 else 2  # small optimization: test 2 then odd primes
    if x > 1:
        result -= result // x
    return result
    
def value_at_index(x: int) -> int:
    """y(x) = 6 * sum_{k=1..x} φ(k), with y(0)=0."""
    if x < 0:
        raise ValueError("x must be non-negative")
    s = 0
    for k in range(1, x + 1):
        s += totient(k)
    return s        
    
def axial_to_cube(coord: HexCoord) -> Tuple[int, int, int]:
    """
    Convert axial (q, r) to cube (x, y, z).
    For the standard pointy-top axial convention:
        x = q
        z = r
        y = -x - z = -q - r
    Returns:
        (x, y, z) integers satisfying x + y + z = 0
    """
    x = coord.q
    z = coord.r
    y = -x - z
    return (x, y, z)

def axial_to_xy(coord: HexCoord, hex_size: float = 1.0) -> Tuple[float, float]:
    """
    Convert axial (q, r) -> 2D Euclidean (x, y) for a pointy-top hex grid.

    This matches your DIRECTIONS convention (pointy-top axial).
    Uses the common "hex radius" size parameter:
      x = sqrt(3) * size * (q + r/2)
      y = (3/2)   * size * r

    Notes
    -----
    - If your `hex_size` is not hex-radius but some other scale, that's fine:
      angles do not depend on scale.
    """
    q, r = coord.q, coord.r
    x = math.sqrt(3.0) * hex_size * (q + 0.5 * r)
    y = 1.5 * hex_size * r
    return (x, y)

def euclid_center_distance(a: HexCoord, b: HexCoord, *, hex_size: float = 1.0) -> float:
    """
    Euclidean distance between the centers of two hexes (pointy-top axial grid).
    """
    ax, ay = axial_to_xy(a, hex_size=hex_size)
    bx, by = axial_to_xy(b, hex_size=hex_size)
    return math.hypot(ax - bx, ay - by)
    
def angle_abc(a: HexCoord, b: HexCoord, c: HexCoord, *,
              hex_size: float = 1.0,
              degrees_out: bool = False) -> float:
    """
    Return the geometric angle at B formed by A-B-C (i.e., ∠ABC).

    Parameters
    ----------
    a, b, c : HexCoord
        Points of the angle (A-B-C).
    hex_size : float
        Same scale you use elsewhere (e.g., grid.hex_size). Scale cancels out for angles.
    degrees_out : bool
        If True, return angle in degrees; otherwise radians.

    Returns
    -------
    float
        Angle at B in radians (default) or degrees.

    Raises
    ------
    ValueError
        If A == B or C == B (undefined angle).
    """
    if a == b or c == b:
        raise ValueError("Angle undefined when A == B or C == B.")

    ax, ay = axial_to_xy(a, hex_size=hex_size)
    bx, by = axial_to_xy(b, hex_size=hex_size)
    cx, cy = axial_to_xy(c, hex_size=hex_size)

    # Vectors BA and BC
    v1x, v1y = (ax - bx), (ay - by)   # BA
    v2x, v2y = (cx - bx), (cy - by)   # BC

    n1 = math.hypot(v1x, v1y)
    n2 = math.hypot(v2x, v2y)
    if n1 == 0.0 or n2 == 0.0:
        raise ValueError("Angle undefined due to zero-length segment (A==B or C==B).")

    dot = v1x * v2x + v1y * v2y
    cos_theta = dot / (n1 * n2)

    # Clamp for floating point safety
    cos_theta = max(-1.0, min(1.0, cos_theta))

    theta = math.acos(cos_theta)
    return math.degrees(theta) if degrees_out else theta


def hex_step_distance(hex_size: float) -> float:
    """Center-to-center distance for one axial step (all 6 neighbors)."""
    return math.sqrt(3.0) * hex_size  # pointy-top tiling


def idx_to_step(i: int) -> Tuple[int, int]:
    return DIRECTIONS[i % 6]


# --- Obstacle map builders (extensible) --------------------------------------
from typing import Dict, Set, Iterable, Optional, List, Tuple, Callable
import random
import math

# If HexCoord is defined above in this file:
# @dataclass(frozen=True)
# class HexCoord:
#     q: int
#     r: int

# -----------------------------------------------------------------------------
# Geometry helpers
# -----------------------------------------------------------------------------
def hex_disk(center: "HexCoord", radius: int) -> Set["HexCoord"]:
    """
    Return all axial hex coordinates within (<=) the given radius from `center`.
    This is the standard axial 'disk' (not just the ring).

    Notes
    -----
    - radius == 0 -> [center]
    - Uses the axial constraints to stay in the hex-shaped bounds.

    Based on the common axial iteration pattern:
      for dq in [-r..+r]:
        for dr in [max(-r, -dq-r) .. min(+r, -dq+r)]:
            (q,r) = (cq + dq, cr + dr)
    """
    cq, cr = center.q, center.r
    cells: Set["HexCoord"] = set()
    for dq in range(-radius, radius + 1):
        rmin = max(-radius, -dq - radius)
        rmax = min(radius,  -dq + radius)
        for dr in range(rmin, rmax + 1):
            cells.add(HexCoord(cq + dq, cr + dr))
    return cells


def hex_step_distance(hex_size: float) -> float:
    """
    Center-to-center distance for one axial step on a pointy-top hex grid.
    """
    return math.sqrt(3.0) * hex_size
def _pixel_to_axial(x_rel: float, y_rel: float, hex_size: float) -> Tuple[float, float]:
    """
    Inverse of axial_to_xy for pointy-top layout (fractional axial coords).

    IMPORTANT:
    - This function expects a *math* coordinate system where:
        x_rel is right-positive
        y_rel is UP-positive
    - Image pixels are y-down, so callers must pass:
        y_rel = (origin_y - pixel_y)
    """
    r = (2.0 / 3.0) * (y_rel / hex_size)
    q = (x_rel / (math.sqrt(3.0) * hex_size)) - (r / 2.0)
    return q, r


def _hex_polygon_vertices(cx: float, cy: float, s: float):
    """Pointy-top hex vertices for a hex of radius s centered at (cx, cy)."""
    for k in range(6):
        ang = math.radians(30 + 60 * k)
        yield (cx + s * math.cos(ang), cy + s * math.sin(ang))


def _make_hex_mask(hex_radius_px: float):
    """
    Precompute a hex mask (boolean array) for sampling pixels inside a hex.

    The mask is centered in its own canvas; later we align it to each hex center
    in image pixel space.
    """
    s = float(hex_radius_px)

    # Pointy-top hex bbox:
    # width  ~= sqrt(3) * s
    # height ~= 2 * s
    w = int(math.ceil(math.sqrt(3.0) * s)) + 3
    h = int(math.ceil(2.0 * s)) + 3

    cx, cy = (w - 1) / 2.0, (h - 1) / 2.0

    img = Image.new("L", (w, h), 0)
    draw = ImageDraw.Draw(img)
    draw.polygon(list(_hex_polygon_vertices(cx, cy, s)), fill=255)

    return (np.array(img) > 0), w, h


def _parse_color(c: Union[str, Tuple[int, int, int]]) -> Tuple[int, int, int]:
    """Accept '#RRGGBB' or (R,G,B) and return (R,G,B)."""
    if isinstance(c, str):
        s = c.strip()
        if s.startswith("#"):
            s = s[1:]
        if len(s) != 6:
            raise ValueError(f"Color string must be '#RRGGBB' (got {c!r})")
        r = int(s[0:2], 16)
        g = int(s[2:4], 16)
        b = int(s[4:6], 16)
        return (r, g, b)
    if (isinstance(c, tuple) and len(c) == 3 and all(isinstance(x, int) for x in c)):
        return c
    raise TypeError("Color must be '#RRGGBB' or (R,G,B) tuple")

def _axial_round(qf: float, rf: float) -> "HexCoord":
    """Round fractional axial coords (q,r) to nearest hex using cube rounding."""
    xf = qf
    zf = rf
    yf = -xf - zf

    rx = round(xf)
    ry = round(yf)
    rz = round(zf)

    x_diff = abs(rx - xf)
    y_diff = abs(ry - yf)
    z_diff = abs(rz - zf)

    if x_diff > y_diff and x_diff > z_diff:
        rx = -ry - rz
    elif y_diff > z_diff:
        ry = -rx - rz
    else:
        rz = -rx - ry

    return HexCoord(int(rx), int(rz))

def _com_of_hexes(hexes: Set["HexCoord"]) -> "HexCoord":
    """Unweighted COM of axial hex coords, rounded back to a HexCoord."""
    qs = [h.q for h in hexes]
    rs = [h.r for h in hexes]
    qf = float(sum(qs)) / len(qs)
    rf = float(sum(rs)) / len(rs)
    return _axial_round(qf, rf)

def image_to_hex_obstacles(
    image_path: str,
    hex_radius_px: float,
    *,
    origin: Union[Literal["center"], Tuple[float, float]] = "center",
    black_threshold: int = 10,
    margin_cells: int = 2,
    start_color: Union[str, Tuple[int, int, int]] = "#FF0000",  # default: red
    goal_color: Union[str, Tuple[int, int, int]] = "#0000FF",   # default: blue
) -> Tuple[Set["HexCoord"], "HexCoord", "HexCoord"]:
    """
    Overlay a pointy-top axial hex grid over an image and classify each hex:

    Priority (descending):
      1) If ANY pixel in the hex is "black" (all channels <= black_threshold) => obstacle/black
      2) Else if the hex is entirely white (all channels == 255) => white (ignored)
      3) Else average RGB inside the hex:
            if avg closer to start_color => start-labeled
            else closer to goal_color => goal-labeled

    Then:
      - If multiple start-labeled hexes exist, pick their COM (center-of-mass) rounded to one hex.
      - Same for goal-labeled.

    Returns:
      (obstacles_set, start_hex, goal_hex)
    """

    if black_threshold < 0:
        raise ValueError("black_threshold must be non-negative")

    start_rgb = np.array(_parse_color(start_color), dtype=np.float32)
    goal_rgb  = np.array(_parse_color(goal_color),  dtype=np.float32)

    # --- load RGB (DO NOT grayscale) ---
    img = Image.open(image_path).convert("RGB")
    arr = np.array(img, dtype=np.uint8)  # (H, W, 3)
    H, W, _ = arr.shape

    # origin in pixel space
    if origin == "center":
        ox, oy = W / 2.0, H / 2.0
    else:
        ox, oy = float(origin[0]), float(origin[1])

    # precompute hex mask
    mask, mw, mh = _make_hex_mask(hex_radius_px)
    hw, hh = mw / 2.0, mh / 2.0

    # compute axial bounds from image corners (y_rel is UP-positive => oy - y)
    corners = [(0.0, 0.0), (W - 1.0, 0.0), (0.0, H - 1.0), (W - 1.0, H - 1.0)]
    qrs = [_pixel_to_axial(x - ox, oy - y, hex_radius_px) for x, y in corners]

    q_min = int(math.floor(min(q for q, _ in qrs))) - margin_cells
    q_max = int(math.ceil (max(q for q, _ in qrs))) + margin_cells
    r_min = int(math.floor(min(r for _, r in qrs))) - margin_cells
    r_max = int(math.ceil (max(r for _, r in qrs))) + margin_cells

    obstacles: Set["HexCoord"] = set()
    start_hexes: Set["HexCoord"] = set()
    goal_hexes: Set["HexCoord"] = set()

    # helper tests (vectorized over pixel list)
    def _any_black(pix: np.ndarray) -> bool:
        # pix shape: (N, 3)
        return bool(np.any(np.all(pix <= black_threshold, axis=1)))

    def _all_white(pix: np.ndarray) -> bool:
        # "entirely white" per your spec: exactly 255,255,255
        return bool(np.all(pix == 255))

    for r in range(r_min, r_max + 1):
        for q in range(q_min, q_max + 1):
            coord = HexCoord(q, r)

            # hex center in pixel coords
            cx_rel, cy_rel = axial_to_xy(coord, hex_size=hex_radius_px)
            cx = ox + cx_rel
            cy = oy - cy_rel

            # mask bbox in pixel coords
            x0 = int(round(cx - hw))
            y0 = int(round(cy - hh))
            x1 = x0 + mw
            y1 = y0 + mh

            # clip to image
            ix0, iy0 = max(0, x0), max(0, y0)
            ix1, iy1 = min(W, x1), min(H, y1)
            if ix0 >= ix1 or iy0 >= iy1:
                continue

            # map into mask coords
            mx0 = ix0 - x0
            my0 = iy0 - y0
            mx1 = mx0 + (ix1 - ix0)
            my1 = my0 + (iy1 - iy0)

            region = arr[iy0:iy1, ix0:ix1, :]   # (h, w, 3)
            m = mask[my0:my1, mx0:mx1]          # (h, w)

            if not region.size:
                continue

            pix = region[m]  # (N,3)
            if pix.size == 0:
                continue

            # Priority 1: black => obstacle
            if _any_black(pix):
                obstacles.add(coord)
                continue

            # Priority 2: entirely white => ignore
            if _all_white(pix):
                continue

            # Priority 3: average color => classify closer to start vs goal
            avg = pix.astype(np.float32).mean(axis=0)  # (3,)
            ds = float(np.linalg.norm(avg - start_rgb))
            dg = float(np.linalg.norm(avg - goal_rgb))

            if ds < dg:
                start_hexes.add(coord)
            else:
                goal_hexes.add(coord)

    if not start_hexes:
        raise ValueError("No start-colored hexes detected (start_hexes empty).")
    if not goal_hexes:
        raise ValueError("No goal-colored hexes detected (goal_hexes empty).")

    start_hex = _com_of_hexes(start_hexes) if len(start_hexes) > 1 else next(iter(start_hexes))
    goal_hex  = _com_of_hexes(goal_hexes)  if len(goal_hexes) > 1 else next(iter(goal_hexes))

    return obstacles, start_hex, goal_hex



# -----------------------------------------------------------------------------
# Obstacle generator registry
# -----------------------------------------------------------------------------
# Signature each generator should follow:
#   gen(center, radius, *, rng, exclude, **kwargs) -> Set[HexCoord]
ObstacleGen = Callable[[ "HexCoord", int], Set["HexCoord"]]

# We'll maintain a registry mapping names -> callables that accept (center, radius, *, rng, exclude, **kwargs)
_OBSTACLE_GENERATORS: Dict[str, Callable[..., Set["HexCoord"]]] = {}

def register_obstacle_generator(name: str, func: Callable[..., Set["HexCoord"]]) -> None:
    """
    Register a new obstacle generator under a short name.

    Each generator must have the signature:
        func(center: HexCoord, radius: int, *, rng: random.Random, exclude: Set[HexCoord], **kwargs) -> Set[HexCoord]
    """
    _OBSTACLE_GENERATORS[name] = func



# -----------------------------------------------------------------------------
# Generator #1: random_n  (uniform random obstacles in the disk)
# -----------------------------------------------------------------------------
def gen_random_obstacles(
    center: "HexCoord",
    radius: int,
    *,
    rng: random.Random,
    exclude: Iterable["HexCoord"] = (),
    n: int,
) -> Set["HexCoord"]:
    """
    Place `n` random obstacles uniformly within the hex disk (<= radius),
    excluding any coordinates passed via `exclude`.

    Parameters
    ----------
    center : HexCoord
        Disk center.
    radius : int
        Disk radius in hex steps.
    rng : random.Random
        RNG instance (for reproducibility).
    exclude : Iterable[HexCoord]
        Coordinates to keep free (e.g., start, goal, reserved path).
    n : int
        Number of obstacles to place (actual placed count may be less if space is limited).

    Returns
    -------
    Set[HexCoord]
        A set with up to `n` random blocked cells.
    """
    excl: Set["HexCoord"] = set(exclude) if exclude else set()
    candidates = [c for c in hex_disk(center, radius) if c not in excl]
    if not candidates or n <= 0:
        return set()

    k = min(n, len(candidates))
    # random.Random.sample requires a sequence
    chosen = rng.sample(candidates, k)
    return set(chosen)


# Register the first generator
register_obstacle_generator("random_n", gen_random_obstacles)


from typing import Iterable, Set
# assumes HexCoord, hex_disk (or _hex_disk), and register_obstacle_generator are already defined

# -----------------------------------------------------------------------------
# Generator #2: fill all  (fill all hexes as obstacles in radius)
# -----------------------------------------------------------------------------
def gen_fill_all(
    center: "HexCoord",
    radius: int,
    *,
    rng,                              # required by the registry; not used here
    exclude: Iterable["HexCoord"] = (),
) -> Set["HexCoord"]:
    """
    Fill the entire allowed disk with cells.

    Intended use:
    - Use with op="add" to make the whole map blocked.
    - Then call other generators with op="carve" (e.g., 'track') to open corridors.

    Parameters
    ----------
    center : HexCoord
        Disk center.
    radius : int
        Disk radius in hex steps.
    rng : random.Random
        Unused; present for signature consistency.
    exclude : Iterable[HexCoord]
        Cells to keep free (e.g., start/goal or reserved anchors).

    Returns
    -------
    Set[HexCoord]
        All cells in the (center, radius) disk, minus 'exclude'.
    """
    # If you already have _hex_disk(center, radius), you can use that instead of hex_disk(...)
    all_cells = set(hex_disk(center, radius))
    return all_cells.difference(set(exclude or []))

# Register it
register_obstacle_generator("fill_all", gen_fill_all)

# -----------------------------------------------------------------------------
# Generator #2: track  (Build a road from start to goal)
# -----------------------------------------------------------------------------

# --- Track generator: 60° turns only, no self-intersection -----------------------
def gen_track_road(
    center: "HexCoord",
    radius: int,
    *,
    rng: random.Random,
    exclude: Iterable["HexCoord"] = (),
    start: "HexCoord",
    goal: "HexCoord",
    # Enforce at least this many 60° turns before connecting to goal
    min_turns: int = 4,
    # Back-compat alias if old code passes "turns"
    turns: Optional[int] = None,
    # Corridor thickness (hex radius): 0 => single-cell line
    thickness: int = 1,
    # Random straight segment length between 60° turns during turn-building phase
    segment_len_min: int = 2,
    segment_len_max: int = 6,
    # Safety caps
    max_steps_build: int = 10000,
    max_steps_connect: int = 10000,
) -> Set["HexCoord"]:
    """
    Build a 'track' (road corridor) from `start` to `goal` that:
      - uses only 60° turns (heading changes of ±1 on the 0..5 ring),
      - never self-intersects (centerline cells are all unique),
      - enforces at least `min_turns` heading changes before attempting to connect to `goal`.

    The route is *not* shortest; it is composed of random-length straight segments
    with 60° direction changes. After achieving `min_turns`, a constrained connection
    phase (using only keep/±60° per step) finishes the path.

    Returns a set of cells to be *carved* (kept free). Use with op="carve".
    """
    # --- parameter normalization ---
    if turns is not None:
        min_turns = turns
    min_turns = max(0, int(min_turns))
    Lmin = max(1, int(segment_len_min))
    Lmax = max(Lmin, int(segment_len_max))
    pad  = max(0, int(thickness))

    # --- bounds & trivial cases ---
    allowed = hex_disk(center, radius)
    if start not in allowed or goal not in allowed:
        return set()  # endpoints outside bounds; nothing to carve

    if start == goal:
        return hex_disk(start, pad) & allowed

    # --- centerline construction with constraints ---
    centerline: list["HexCoord"] = [start]
    visited: Set["HexCoord"] = {start}   # prevent self-intersection

    # Pick an initial heading (0..5). If you prefer biasing toward goal, you can
    # seed this with a direction that reduces distance from start.
    heading = rng.randrange(6)
    turns_done = 0
    steps_done = 0

    # ------------------
    # Phase 1: build at least `min_turns` 60° turns
    # ------------------
    while turns_done < min_turns and steps_done < max_steps_build:
        # Walk a straight segment of random length L in the *current* heading.
        L = rng.randint(Lmin, Lmax)
        for _ in range(L):
            nxt = _step(centerline[-1], heading)

            # If next step violates bounds or revisits a cell, try steering ±60°
            if nxt not in allowed or nxt in visited:
                candidates = [_dir_left(heading), _dir_right(heading)]
                rng.shuffle(candidates)  # randomize left/right preference
                chosen = None
                for h2 in candidates:
                    t = _step(centerline[-1], h2)
                    if t in allowed and t not in visited:
                        chosen = h2
                        nxt = t
                        break
                if chosen is None:
                    # Can't proceed further in this phase; give up building more here
                    break
                # We turned by ±60° (compliant) and used a step; count it as a turn
                heading = chosen
                turns_done += 1

            # Commit the step
            centerline.append(nxt)
            visited.add(nxt)
            steps_done += 1

            if steps_done >= max_steps_build:
                break

        if steps_done >= max_steps_build:
            break

        # Enforce a 60° turn between segments (if we can move at least 1 step)
        # Choose left or right randomly; only ±1 is allowed
        candidates = [_dir_left(heading), _dir_right(heading)]
        rng.shuffle(candidates)
        turned = False
        for h2 in candidates:
            # Turning itself doesn't move; we’ll move in Phase 1’s next segment loop.
            # But we also need to ensure the *first* step after turn will be legal.
            t = _step(centerline[-1], h2)
            if t in allowed and t not in visited:
                heading = h2
                turns_done += 1
                turned = True
                break
        # If we couldn't commit to a turn heading now, we’ll let the next loop
        # attempt to steer on the first step anyway (still 60° only).

    # ------------------
    # Phase 2: connect to goal using only keep/±60° per step, no self-intersections
    # ------------------
    it = 0
    while centerline[-1] != goal and it < max_steps_connect:
        it += 1
        cur = centerline[-1]

        # Candidates limited to keep/±60°
        candidates = [heading, _dir_left(heading), _dir_right(heading)]

        # Score candidates: prefer those that reduce distance to goal; otherwise equal distance
        cur_d = hdist(cur, goal)
        scored: list[tuple[int, int]] = []  # (priority, dir)
        for h2 in candidates:
            nxt = _step(cur, h2)
            if nxt not in allowed or nxt in visited:
                continue  # must stay in bounds and avoid self-intersection
            d = hdist(nxt, goal)
            if d < cur_d:
                scored.append((0, h2))   # best: reduces distance
            elif d == cur_d:
                scored.append((1, h2))   # neutral: equal distance
            else:
                scored.append((2, h2))   # worse: increases distance (allowed if needed)

        if not scored:
            # Stuck: try a gentle random wobble (still keep/±60°), but we already filtered those
            break

        # Pick a candidate with the best priority, break ties randomly
        best_pri = min(p for p, _ in scored)
        options  = [d for p, d in scored if p == best_pri]
        rng.shuffle(options)
        chosen = options[0]

        # Count a turn if we changed heading by ±1
        if chosen != heading:
            # Because candidates are only keep/±60°, any change is a 60° turn
            turns_done += 1

        heading = chosen
        nxt = _step(cur, heading)
        centerline.append(nxt)
        visited.add(nxt)

    # Attempt a final hop if we are adjacent to goal and haven’t stepped on it yet
    if centerline[-1] != goal:
        cur = centerline[-1]
        for i in range(6):
            if _step(cur, i) == goal and goal in allowed and goal not in visited:
                # Only accept if i is keep/±60° relative to current heading
                if i in (heading, _dir_left(heading), _dir_right(heading)):
                    centerline.append(goal)
                    visited.add(goal)
                break

    # --- Thicken the centerline into a corridor and clip to the allowed disk ---
    road_set: Set["HexCoord"] = set()
    if pad == 0:
        for c in centerline:
            if c in allowed:
                road_set.add(c)
    else:
        for c in centerline:
            road_set |= (hex_disk(c, pad) & allowed)

    # Ensure endpoints included (thickened)
    road_set |= (hex_disk(start, pad) & allowed)
    road_set |= (hex_disk(goal,  pad) & allowed)

    return road_set


# Register
register_obstacle_generator("track", gen_track_road)


# -----------------------------------------------------------------------------
# Main builder: call a sequence of generator "types" and merge their outputs
# -----------------------------------------------------------------------------


def build_obstacle_map(
    center: "HexCoord",
    radius: int,
    *,
    types: Iterable[tuple] = (),
    exclude: Iterable["HexCoord"] = (),
    seed: Optional[int] = None,
) -> Dict["HexCoord", bool]:
    """
    Build an obstacle map (Dict[HexCoord, True]) by applying a sequence of
    named obstacle generators.

    Each entry in `types` can be:
        (name, params)                    # op defaults to "add"
      or (name, params, op)               # op in {"add","carve"}

    Or put "op" into params: {"op": "carve", ...} (we will strip it).
    """
    rng = random.Random(seed)
    keep_free: Set["HexCoord"] = set(exclude) if exclude else set()
    blocked: Set["HexCoord"] = set()

    for entry in types:
        # Normalize (name, params, op)
        if len(entry) == 2:
            name, params = entry
            op = (params or {}).get("op", "add")
        elif len(entry) == 3:
            name, params, op = entry
        else:
            raise ValueError("Each 'types' entry must be (name, params) or (name, params, op)")

        if name not in _OBSTACLE_GENERATORS:
            raise KeyError(f"Unknown obstacle generator '{name}'. "
                           f"Available: {sorted(_OBSTACLE_GENERATORS.keys())}")

        gen = _OBSTACLE_GENERATORS[name]

        # --- DO NOT forward 'op' to the generator ---
        params = dict(params or {})
        params.pop("op", None)

        # Respect current exclusions and already-blocked cells
        local_exclude = keep_free.union(blocked)

        produced = gen(center, radius, rng=rng, exclude=local_exclude, **params)

        if op == "add":
            blocked |= produced
        elif op == "carve":
            blocked -= produced
            keep_free |= produced
        else:
            raise ValueError(f"Unsupported op='{op}'. Use 'add' or 'carve'.")

    return {c: True for c in blocked}


# -----------------------------------------------------------------------------
# Misc Helper Functions
# -----------------------------------------------------------------------------
# --- Utilities ---------------------------------------------------------------
def hdist(a: "HexCoord", b: "HexCoord") -> int:
    """Axial hex Manhattan distance (# of steps)."""
    dq = abs(a.q - b.q)
    dr = abs(a.r - b.r)
    ds = abs((-a.q - a.r) - (-b.q - b.r))
    return (dq + dr + ds) // 2

def _hex_disk(center: "HexCoord", r: int) -> Set["HexCoord"]:
    """Closed disk (<= r) around center in axial coords."""
    if r < 0:
        return set()
    cq, cr = center.q, center.r
    out: Set["HexCoord"] = set()
    for dq in range(-r, r + 1):
        rmin = max(-r, -dq - r)
        rmax = min(r,  -dq + r)
        for dr in range(rmin, rmax + 1):
            out.add(HexCoord(cq + dq, cr + dr))
    return out

def _step(a: "HexCoord", dir_idx: int) -> "HexCoord":
    dq, dr = DIRECTIONS[dir_idx % 6]
    return HexCoord(a.q + dq, a.r + dr)

def _dir_left(h: int) -> int:  return (h - 1) % 6  # -60°
def _dir_right(h: int) -> int: return (h + 1) % 6  # +60°

    

# -----------------------------------------------------------------------------
# Optional convenience: build a HexGrid directly from generators
# -----------------------------------------------------------------------------
def make_grid_with_obstacles(
    hex_size: float,
    center: "HexCoord",
    radius: int,
    *,
    types: Iterable[Tuple[str, Dict]] = (),
    exclude: Iterable["HexCoord"] = (),
    seed: Optional[int] = None,
) -> "HexGrid":
    """
    Convenience: create a HexGrid with obstacles built via the given generator
    sequence. You can still add/remove obstacles later on the grid if needed.
    """
    obstacles = build_obstacle_map(center, radius, types=types, exclude=exclude, seed=seed)
    return HexGrid(hex_size=hex_size, obstacles=obstacles)


